pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.13.x'
  displayName: 'Install Node.js 10.13.0'

- script: |
    npm config set loglevel warn
    npm ci
  displayName: 'npm ci'

- script: |
    git config user.email team+camperbot@freeCodeCamp.org
    git config user.name "CamperBot"
    npm run test
  displayName: 'npm run test'

- task: PublishTestResults@2
  condition: always()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'client/junit.xml' 
    testRunTitle: 'Client'
