pool:
  vmImage: 'Ubuntu-16.04'

steps:

- script: |
    node --version
    echo $(which node --all)
    echo $(printenv)
  displayName: 'Show node info'

- task: NodeTool@0
  inputs:
    versionSpec: '10.13.x'
  displayName: 'Install Node.js 10.13.0'

- script: |
    npm config set loglevel warn
    npm ci
  displayName: 'npm ci'

- script: |
    git config user.email team+camperbot@freeCodeCamp.org
    git config user.name "CamperBot"
    node ./locale.js
    npm run test
  displayName: 'npm run test'

- script: |
    ulimit -a
    sudo lsof +D $(Build.Repository.LocalPath) | awk '{print $1}' | uniq -c | sort -n
  condition: always() 
  displayName: 'Show open files, etc'

- task: PublishTestResults@2
  condition: always()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'client/junit.xml' 
    testRunTitle: 'Client'
